Hacer llamadas
Roberto-Ruiz-Obregon/AndroidApp pull request #6
Opened 2023-03-15 22:21 UTC by MonseMoreno

2023-03-15 22:23 UTC, Leonardo812 approved these changes
Funciona, apruebo merge 👍

2023-03-15 22:26 UTC, CesarJimenezVilleda02 requested changes

2023-03-15 22:26 UTC, CesarJimenezVilleda02 commented on app/src/main/java/com/example/kotlin/robertoruizapp/framework/view/fragments/FragmentoHome.kt
> +            val phone  = "tel:" + binding.telefono.text.toString()
Mover esta funcion a otro metodo y asignarlo como onClickListener. Revisar la arquitectura MVVM y CLEAN para ver si esta funcionalidad correspode al fragmento @felix-rojas tienes alguna idea de si es correcto?

2023-03-16 00:10 UTC, CesarJimenezVilleda02 approved these changes

2023-03-16 00:12 UTC, Lalo2077 approved these changes
Esta bien implementado y la funcionalidad se ve bien.

2023-03-16 00:35 UTC, DenisseDB approved these changes

2023-03-16 00:58 UTC, merged